#!/bin/bash

#! Build Variables

echo What is the IP address of your Modem
read var_mdm

echo What is the password for your Modem
read var_mdm_pass

#! Configure 9_mdm_reset

sudo touch /home/pi/9_mdm_reset
sudo chmod 777 /home/pi/9_mdm_reset

echo sshpass -p "$var_mdm_pass" ssh -o StrictHostKeyChecking=no admin@$var_mdm set /control/wan/devices/mdm*/reset true >> /home/pi/9_mdm_reset
