#!/bin/bash
cd /home/pi

#! Build variables
echo What is the hostname of this PI [UKWD-APNPI-WGN-205]
read var_hostname

echo What is the IP Address of your Modem
read var_mdm

echo What is the IP Address of your Public CURL endpoint
read var_pubcurl

echo What is the IP Address of your Private CURL endpoint
read var_privcurl

echo What is the IP Address of your primary DNS endpoint
read var_dns1

echo What is the IP Address of your secondary DNS endpoint
read var_dns2

echo Are these variables correct?

echo Hostname = $var_hostname

echo Modem = $var_mdm

echo Public CURL endpoint = $var_pubcurl

echo Private CURL endpoint = $var_privcurl

echo Primary DNS endpoint = $var_dns1
 
echo Secondary DNS endpoint = $var_dns2

select yn in "Yes" "No"; do
	case $yn in
		No ) exit;;
		Yes ) break;;
	esac
done

#! Download configuration files

wget http://52.56.99.9/build/radius_mon_build

wget http://52.56.99.9/build/snmpd.conf.emea

wget http://52.56.99.9/build/ssh_start

#! Install Applications

sudo apt-get update -q
sudo apt-get install snmpd snmp sshpass dnsutils -y -q

#! Configure Headless SSH PI

sudo chmod 777 /home/pi/ssh_start

#! Configure SNMP

sudo rm /etc/snmp/snmpd.conf
sudo mv ./snmpd.conf.emea /etc/snmp/snmpd.conf
sudo systemctl restart snmpd

#! Configure CURL routes

sudo touch /home/pi/1_routes
sudo chmod 777 /home/pi/1_routes

echo sudo route add -host $var_pubcurl gw $var_mdm >> /home/pi/1_routes
echo sudo route add -host $var_privcurl gw $var_mdm >> /home/pi/1_routes
echo sudo route add -host $var_dns1 gw $var_mdm >> /home/pi/1_routes
echo sudo route add -host $var_dns2 gw $var_mdm >> /home/pi/1_routes

#! Build rc.local

sudo sed -i "20i /home/pi/ssh_start &" /etc/rc.local
sudo sed -i "21i /home/pi/1_routes &" /etc/rc.local

#! Configure Hostname

sudo sed -i -e 's/'raspberrypi'/'$var_hostname'/g' /etc/hosts
sudo sed -i -e 's/'raspberrypi'/'$var_hostname'/g' /etc/hostname

#! Restart

sudo init 6






